### ISSUE TITLE
Please allow text>=2.0 && <2.2

### ISSUE THREAD

**Issue by prolic** [sayo-hs/data-effects#1]
I run into compatibility issues and cannot install this library otherwise.

**Comment by ymdfield** [comment]
Thank you for the report! I have uploaded the revised version to Hackage (v0.1.2). If there are any other version issues, please report them again.

36b97df1d80f3e0e2b824b228d46aff99f12355c

**Comment by prolic** [comment]
Appreciate it, thanks!
